name: divyang_pimpri_chinchwad_municipal_corporation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8
  
  # Media & Camera
  camera: ^0.11.2  
  image_picker: ^1.2.0
  flutter_image_compress: ^2.4.0
  image: ^4.5.2
  video_compress: ^3.1.4
  video_player: ^2.10.0
  
  # Location
  geocoding: ^4.0.0
  geolocator: ^13.0.2
  
  # Network & Web
  http: ^1.6.0
  http_parser: ^4.1.2
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.2
  
  # Utilities
  intl: ^0.20.2
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  fluttertoast: ^8.2.12
  
  # State Management & Storage
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  gson: ^0.1.6-dev
  
  # UI & Animations
  lottie: ^3.3.0
  flutter_screenutil: ^5.9.3
  
  # App Management
  in_app_update: ^4.2.5
  rename: ^3.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  image_path: "assets/icon/launcher_icon.png"  

flutter:
  uses-material-design: true

  assets:
     - assets/images/document_image.png
     - assets/images/pmc_logo.jpeg
     - assets/icon/Bank_of_Maharashtra_logo.png
     - assets/icon/policy_image.png
     - assets/images/pcmc_logo.jpeg
     - assets/images/capture_image.jpeg
     - assets/icon/launcher_icon.png
     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
